name: Build Graph

on:
  schedule:
    - cron: '1 11 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest
    steps:
      - uses: avinal/Profile-Readme-WakaTime@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH: "main"
          COMMIT_MSG: "new stats received :dog:"
          STATS_RANGE: last_30_days
